[project]
name = "esingest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "elasticsearch>=9.0.2",
    "locust>=2.37.10",
    "nltk>=3.9.1",
]
